name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and push backend image
      run: |
        docker build -t ian1dunn/linkshortener-backend:latest ./backend
        docker push ian1dunn/linkshortener-backend:latest

    - name: Build and push frontend image
      run: |
        docker build -t ian1dunn/linkshortener-frontend:latest ./frontend
        docker push ian1dunn/linkshortener-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to DigitalOcean Droplet
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.DIGITALOCEAN_DROPLET_IP }}
        username: ${{ secrets.DIGITALOCEAN_DROPLET_USERNAME }}
        password: ${{ secrets.DIGITALOCEAN_DROPLET_PASSWORD }}
        port: 22
        script: |
          cd ~/linkshortener
          sudo docker compose down
          sudo docker compose pull
          sudo docker compose --profile prod up -d